// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class NetDesignItem
    {
        public int DesignItemNo { get; set; }
        public int DesignTool { get; set; }
        public int QuoteNo { get; set; }
        public int? Version { get; set; }
        public int? Order { get; set; }
        public string Language { get; set; }
        public string ProjectNo { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ItemCategoryCode { get; set; }
        public decimal EquivalentUnits { get; set; }
        public string Color { get; set; }
        public string ExteriorColor { get; set; }
        public string InteriorColor { get; set; }
        public string SortName { get; set; }
        public decimal LengthMm { get; set; }
        public string System { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public decimal Amperage { get; set; }
        public string Geometry { get; set; }
        public int? QtyPerRack { get; set; }
        public string DelicateImmersion { get; set; }
        public string DifficultRinsing { get; set; }
        public string LiftType { get; set; }
        public DateTime? CreationTimestamp { get; set; }
        public string CreationUser { get; set; }
        public DateTime? ModificationTimestamp { get; set; }
        public string ModificationUser { get; set; }
    }
}