// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class NetSalesQuoteRelease
    {
        public int SalesQuoteReleaseNo { get; set; }
        public int DesignTool { get; set; }
        public int Numero { get; set; }
        public int Version { get; set; }
        public int Order { get; set; }
        public int? Lot { get; set; }
        public string SalesQuoteNo { get; set; }
        public int ReleaseNo { get; set; }
        public int LineReferenceNo { get; set; }
        public string ProjectNo { get; set; }
        public decimal Quantity { get; set; }
        public DateTime CreationTimestamp { get; set; }
        public string CreationUser { get; set; }
        public DateTime ModificationTimestamp { get; set; }
        public string ModificationUser { get; set; }
    }
}