// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class NetSalesQuoteItem
    {
        public int SalesQuoteItemNo { get; set; }
        public int DesignTool { get; set; }
        public int Numero { get; set; }
        public int Version { get; set; }
        public int Order { get; set; }
        public int SortOrder { get; set; }
        public string Langue { get; set; }
        public string SalesQuoteNo { get; set; }
        public int LineReferenceNo { get; set; }
        public string ProjectNo { get; set; }
        public int? ItemType { get; set; }
        public string ItemNo { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public DateTime? ShipmentDate { get; set; }
        public DateTime? CreationTimestamp { get; set; }
        public string CreationUser { get; set; }
        public DateTime? ModificationTimestamp { get; set; }
        public string ModificationUser { get; set; }
    }
}