// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class RelationPosteDeTravail
    {
        public int Id { get; set; }
        public string PosteTravail { get; set; }
        public string Departement { get; set; }
        public string CategorieProduit { get; set; }
        public string AtelierNav { get; set; }
        public string RoutingLinkCode { get; set; }
        public bool? Active { get; set; }
    }
}