// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class RelationItemCategoryCode
    {
        public int NoCategory { get; set; }
        public string System { get; set; }
        public string Name { get; set; }
        public string CatégorieNav { get; set; }
        public string CatégorieBatch { get; set; }
        public bool? Active { get; set; }
    }
}