// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class RelationAtelier
    {
        public int Id { get; set; }
        public string NoWorkCenter { get; set; }
        public string NomAtelier { get; set; }
    }
}