// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class RelationConfigurationCouleur
    {
        public int ConfigurationCode { get; set; }
        public string Couleur { get; set; }
        public string CouleurInterieur { get; set; }
        public string CouleurExtérieur { get; set; }
    }
}