// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageGroupes
    {
        public int IdGroupe { get; set; }
        public int TypeGroupe { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}