// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageOptimisation
    {
        public Guid DocumentId { get; set; }
        public int? NumeroOptimization { get; set; }
        public DateTime DateDeFin { get; set; }
        public short? SectionsUtilisees { get; set; }
        public string Description { get; set; }
        public DateTime DateDeDebutAtelier { get; set; }
        public DateTime DateDeFinAtelier { get; set; }
        public short? Semaine { get; set; }
        public short? ListeDeProduction { get; set; }
        public string Type { get; set; }
        public int? Responsable { get; set; }
        public DateTime DateMajStock { get; set; }
        public DateTime DateDuCalcul { get; set; }
        public DateTime DateBesoinMateriel { get; set; }
        public short NiveauOptimization { get; set; }
        public short DontUseWasteInterval { get; set; }
        public short NonForcerTigeMax { get; set; }
        public short LonguePiece1 { get; set; }
        public short Tige1Fenetre1 { get; set; }
        public short TypeFente { get; set; }
        public short? CodeEntrepot { get; set; }
        public DateTime DatePlanifiee { get; set; }
        public short? SemainePlanifiee { get; set; }
        public DateTime DateReelBesoinMateriel { get; set; }
        public DateTime DateDeCalculReel { get; set; }
        public DateTime DateReelMajMateriel { get; set; }
        public DateTime DateReelDebutAchat { get; set; }
        public DateTime DateReelFinAchat { get; set; }
        public short RabaisMateriel { get; set; }
        public short DetailleePar { get; set; }
        public short ModeTigeMultiple { get; set; }
        public DateTime DateDeCalculReelUtc { get; set; }
        public short EnUtilisation { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}