// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageEmploye
    {
        public int Code { get; set; }
        public string NomEmploye { get; set; }
        public string Identifiant { get; set; }
        public DateTime? DateDeCreation { get; set; }
    }
}