// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMaterielProject
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public string Reference { get; set; }
        public int ConfigurationCouleur { get; set; }
        public int Quantite { get; set; }
        public decimal Longueur { get; set; }
        public decimal Hauteur { get; set; }
        public decimal AngleCoupeA { get; set; }
        public decimal AngleCoupeB { get; set; }
        public short Complexe { get; set; }
        public int IdMateriel { get; set; }
        public int IdPeinture { get; set; }
        public short Angle { get; set; }
        public short Peinture { get; set; }
        public short Composite { get; set; }
        public short Composante { get; set; }
        public int NoVerre { get; set; }
        public short Demonte { get; set; }
        public short IdEtalonPeinture { get; set; }
        public short IdSousModele { get; set; }
        public string Param { get; set; }
        public int ConfigurationCouleurMaterielBrut { get; set; }
        public decimal Poid { get; set; }
        public int? CodeTypeProduit { get; set; }
        public short InstanceClasseTraitement { get; set; }
        public short? CoteModel { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}