// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageDetailProject
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public short SortOrdre { get; set; }
        public string Type { get; set; }
        public int SousType { get; set; }
        public string Nomenclature { get; set; }
        public string Concept { get; set; }
        public string Description { get; set; }
        public double? Quantité { get; set; }
        public double? CoutUnitaire { get; set; }
        public double? PrixUnitaire { get; set; }
        public string Mesures { get; set; }
        public int? TypeDeCadre { get; set; }
        public int? NombreDeFeuille { get; set; }
        public int? NombreDePoteau { get; set; }
        public string System { get; set; }
        public int? ProductType { get; set; }
        public DateTime? DateModifMateriel { get; set; }
        public DateTime? DateModifMainOeuvre { get; set; }
        public DateTime? DateModifBackground { get; set; }
    }
}