// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageDetailDescriptionProject
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public string Langue { get; set; }
        public string Description { get; set; }
        public string DescriptionAuto { get; set; }
        public string DescriptionProd { get; set; }
        public string Couleur { get; set; }
        public DateTime DateCreation { get; set; }
        public DateTime DateModification { get; set; }
    }
}