// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageProjet
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public string NumeroCommande { get; set; }
        public DateTime? DateDeDemande { get; set; }
        public short Type { get; set; }
        public string Projet { get; set; }
        public short SubType { get; set; }
        public int? NumerationId { get; set; }
        public string Reference { get; set; }
        public int? CodeUtilisateur { get; set; }
        public string NomClient { get; set; }
        public string NomUtilisateur { get; set; }
        public DateTime DateDeConfirmation { get; set; }
        public short Confirmation { get; set; }
        public DateTime? PretProduction { get; set; }
        public short Active { get; set; }
        public string NomDeVersion { get; set; }
        public int NumeroSousComm { get; set; }
        public int? CopieDeVersion { get; set; }
        public int? CodeClient { get; set; }
        public string Nom { get; set; }
        public DateTime DateDAcceptation { get; set; }
        public DateTime DateDeDecoupe { get; set; }
        public DateTime DateCompte { get; set; }
        public DateTime? DateDeLivraison { get; set; }
        public int? Langue { get; set; }
        public string Contact { get; set; }
        public string Information { get; set; }
        public DateTime? DateModifSyst { get; set; }
        public int EtatDeProduction { get; set; }
        public DateTime DateDePlanif { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}