// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMateriel
    {
        public string ReferenceBase { get; set; }
        public string Reference { get; set; }
        public string NoArticlePref { get; set; }
        public string NoArticleNav { get; set; }
        public int ConfigurationCode { get; set; }
        public string Couleur { get; set; }
        public float Longueur { get; set; }
        public decimal Perte { get; set; }
        public short UtilisationPerte { get; set; }
        public string UdMPref { get; set; }
        public string UdMNav { get; set; }
        public int? Facteur { get; set; }
        public bool? Active { get; set; }
        public bool? EstNavrelated { get; set; }
        public bool? EstAssemblage { get; set; }
        public bool? EstBom { get; set; }
        public bool? EstIndependant { get; set; }
        public bool? EstArticlePeint { get; set; }
        public bool? EstAssemblagePeint { get; set; }
        public DateTime DateDeCreation { get; set; }
        public DateTime DateDeModif { get; set; }
    }
}