// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMainOeuvreOptimization
    {
        public int Id { get; set; }
        public int NumeroOptimization { get; set; }
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public int SousModele { get; set; }
        public string PosteTravail { get; set; }
        public float Secondes { get; set; }
        public int Quantite { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}