// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageTempsMateriel
    {
        public string PosteTravail { get; set; }
        public string ReferenceBase { get; set; }
        public float? A0 { get; set; }
        public float? A1 { get; set; }
        public float? B0 { get; set; }
        public float? B1 { get; set; }
        public float? D0 { get; set; }
        public float? K0 { get; set; }
        public float? K1 { get; set; }
        public DateTime DateCreation { get; set; }
        public DateTime DateModification { get; set; }
    }
}