// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageLotMiseEnProductionProjet
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public short Instance { get; set; }
        public short SousModele { get; set; }
        public int? Lot { get; set; }
        public int? Ensemble { get; set; }
        public int PositionEnsemble { get; set; }
        public DateTime? DateEntreeAchat { get; set; }
        public DateTime? DateSortieAchat { get; set; }
        public DateTime? DateExpedition { get; set; }
        public DateTime? DateLivraison { get; set; }
    }
}