// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageBesoinMaterielParent
    {
        public int? Numero { get; set; }
        public int? Version { get; set; }
        public int? EnsembleProduction { get; set; }
        public int? CodeBesoinProduction { get; set; }
        public short Mnset { get; set; }
        public DateTime DateDeCalcul { get; set; }
        public short? Obsolete { get; set; }
        public string Description { get; set; }
        public short TypeMnset { get; set; }
        public DateTime DateDeCalculUtc { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}