// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StagePosteDeTravail
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public int Version { get; set; }
        public int Ordre { get; set; }
        public string PosteTravail { get; set; }
        public float? Secondes { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}