// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMainOeuvreProjet
    {
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public short IdSousModele { get; set; }
        public string PosteTravail { get; set; }
        public float Secondes { get; set; }
        public int IdMainOeuvre { get; set; }
        public int? CodeTypeProduit { get; set; }
        public short InstanceClasseTraitement { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}