// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMainOeuvrePoste
    {
        public Guid RowId { get; set; }
        public string PosteTravail { get; set; }
        public int CodePosteTravail { get; set; }
        public int? Operateur { get; set; }
        public int? Zone { get; set; }
        public short? IdGroupeBudget { get; set; }
        public double? Cout { get; set; }
        public short EstTacheOuvrier { get; set; }
        public short Variable { get; set; }
        public DateTime DateCreation { get; set; }
        public DateTime DateModification { get; set; }
    }
}