// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageTypeProduits
    {
        public int Code { get; set; }
        public string TypeProduit { get; set; }
        public short Classe { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}