// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class StageMaterielOptimization
    {
        public int Id { get; set; }
        public int NumeroOptimization { get; set; }
        public int Numero { get; set; }
        public int Version { get; set; }
        public short Ordre { get; set; }
        public int SousModele { get; set; }
        public string Reference { get; set; }
        public int ConfigCouleur { get; set; }
        public int QuantitéParFenêtre { get; set; }
        public int Quantité { get; set; }
        public decimal Longueur { get; set; }
        public decimal Hauteur { get; set; }
        public decimal AngleCoupeA { get; set; }
        public decimal AngleCoupeB { get; set; }
        public short Complexe { get; set; }
        public int IdMateriel { get; set; }
        public int IdPeinture { get; set; }
        public short Angle { get; set; }
        public short Peinture { get; set; }
        public short Composite { get; set; }
        public short Composante { get; set; }
        public int NoVerre { get; set; }
        public short Demonte { get; set; }
        public short IdEtalonPeinture { get; set; }
        public short? LieuDeTravail { get; set; }
        public string RefOriginal { get; set; }
        public decimal Poid { get; set; }
        public short? CoteModele { get; set; }
        public DateTime? DateDeCreation { get; set; }
        public DateTime? DateDeModif { get; set; }
    }
}