// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrevostApp.Data.Models
{
    public partial class TraceTableIntergiciel
    {
        public int Numero { get; set; }
        public int Commande { get; set; }
        public int Version { get; set; }
        public string Nom { get; set; }
        public string NomOriginal { get; set; }
        public string Description { get; set; }
        public int CompteRangeTable { get; set; }
        public DateTime CreateDateTime { get; set; }
    }
}